services:
  paint-index:
    image: ghcr.io/diptamahardhika/paint-index:v1.0.0-beta.4
    container_name: paint-index-app
    pull_policy: always
    ports:
      - "8081:80"
    restart: unless-stopped
    volumes:
      - ./firebase.js:/usr/share/nginx/html/firebase.js:ro
